name: Exemplo de fluxo de trabalho # nome do workflow

on: # qual evento dispara o workflow
  workflow_dispatch: # fluxo pode ser ativado de forma manual

jobs: # declaração dos jobs
  acao_inicial_job: # nome do job
    runs-on: ubuntu-latest # onde será executado, máquina virtual (runner)
    steps: # declaração dos passos do job
      - name: Imprime Ola # nome do primeiro passo
        run: echo "Ola" # execução de um comando, script ou ação
      - name: Impreme Tchau # nome do segundo passo
        run: echo "Tchau" # execuão do comando...
